### ISSUE TITLE
Km button?

### ISSUE THREAD

**Issue by bmikolaj** [COSC481W-2019Winter/classproject-sudo-give_us_an_a#16]
Maybe a desired feature if we have time could be a mi/km toggle button.

**Comment by bmikolaj** [comment]
Perhaps use feet and meters instead of miles.

**Comment by elawton333** [comment]
Possibly a menu bar with settings for the user to determine once. Not a button the appears on the parked screen every time.

**Comment by elawton333** [comment]
resolved in sprint 2
