### ISSUE TITLE
Park Here button too low

### ISSUE THREAD

**Issue by bmikolaj** [COSC481W-2019Winter/classproject-sudo-give_us_an_a#17]
On some phones (mine) the bottom bar for going back or home is an overlay and thus covers up the park here button.

**Comment by elawton333** [comment]
Resolved on 3/11/19

**Comment by bmikolaj** [comment]
ParkedActivity is too low too. When you press park, the delete parking spot button is still at the very bottom and covered up by bottom bar.

**Comment by elawton333** [comment]
resolved
